package com.hyva.bsfms.bs.bspojo;
import com.hyva.bsfms.bs.bsentities.Student;
import com.hyva.bsfms.bs.bsentities.StudentFee;
import lombok.Data;

import java.sql.Date;
import java.util.List;
@Data
public class StudentFeeDto {
    private Long studentFeeId;
    private Double totalFeeAmount;
    private String StudentName;
    private String fatherName;
    private Student student;
    private StudentFee studentFee;
    private String motherName;
    private Long studentId;
    private int noOfInstallments;
    private String paymentType;
    private Double paidAmount;
    private String chequeNo;
    private String bankName;
    private String cardNo;
    private String status;
    private String approvalCode;
    private Date paymentDate;
    private Date chequeDate;
    private Double feeTypeAmount;
    private Double totalPayable;
    private Double totalPaid;
    private Double dueAmount;
    private Double totalDueAmount;
    private Double payingFee;
    private String gradeName;
    private Long gradeId;
    private String academicYear;
    private String receiptNo;
    private String bankDetails;
    private String cardDetails;
    private String studentProfileId;
    private Double bankAmt;
    private Double cardAmt;
    private Double cashAmt;
    private Long academicYearId;
    private Long receiptId;
    private Boolean checkBox;
    private List<StudentFeeDetailsPojo> studentFeeDetailsPojoList;
    private String chequeStatus;
    private String studentType;
}
