package com.hyva.bsfms.pusher.pusherMapper;
import com.hyva.bsfms.bs.bspojo.FeeTypeMasterPojo;
import com.hyva.bsfms.bs.bspojo.StudentFeeDto;
import com.hyva.bsfms.bs.bspojo.StudentFeePojo;
import com.hyva.bsfms.bs.bspojo.StudentPojo;
import com.hyva.bsfms.pusher.pusherPojo.TransactionPojo;
import com.hyva.bsfms.pusher.pusherPojo.TransactionPojo.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransactionMapper {
    public static List<SelectedItem> getItemToFee(StudentPojo pojo1){
        List<SelectedItem> selectedItemsLIst=new ArrayList<>();
       for(FeeTypeMasterPojo ss: pojo1.getFeeTypeMasterPojoList()) {
           TransactionPojo.SelectedItem selectedItem;
           selectedItem = new SelectedItem();
           // selectedItem.setItemName("itemA");
           selectedItem.setItemName(ss.getFeeTypeName());
           selectedItem.setQty(1);
           selectedItem.setUomName("Unit");
//           selectedItem.setConvertedQuantity(0);
//           selectedItem.setRemainingQty(1);
           selectedItem.setAmtinclusivetax(ss.getFeeAmount());
           selectedItem.setAmtexclusivetax(ss.getFeeAmount());
           selectedItem.setUnitPrice(ss.getFeeAmount());
           selectedItem.setItemAmount(ss.getFeeAmount());
           selectedItemsLIst.add(selectedItem);
//           selectedItem.setItemCode("ITEM02");
//           selectedItem.setItemDescription("laaa");
//           selectedItem.setItemId(4);
           selectedItem.setTaxid(2);
           selectedItem.setTaxamt(0d);
           selectedItem.setTaxName(" GST-5 ");
           selectedItem.setTaxpercent(5);
           //  selectedItem.setSerializableStatus("Bulk");
           //   selectedItem.setInclusiveJSON("{\"purchases\":false,\"sales\":false}");
           //    selectedItem.setUomName("Unit");
           //  selectedItem.setHsnCode("01");
           //     selectedItem.setUom("0");
           //selectedItem.setServiceDescription("InActive");
       }
        return selectedItemsLIst;
    }
    public static TransactionPojo studentToTransaction(StudentPojo pojo1) {
        TransactionPojo pojo = new TransactionPojo();
        pojo.setCheckForHoldStock(true);
        pojo.setCustomerName(pojo1.getStudentName());
   //   pojo.setCustomerName(pojo1.getStudentName());
        pojo.setTotalTaxAmt(0d);
    //  pojo.setFrom_reg("8E3EDC7218954E18");
        pojo.setFrom_reg("7F5F522AFBB14D4E");
        pojo.setTo_reg("7F5F522AFBB14D4E");
        pojo.setSubscriptionType("DesktopWithRTR");
        pojo.setTypeDoc("SIN");
        pojo.setMemo("Fee Payment");
        pojo.setType_flag("Purchase");
    //  pojo.setType_flag("Sales");
        pojo.setSiNo(pojo1.getStudentProfileId());
        pojo.setPaymentType("multiPayment");
        pojo.setDateOfInvoice(new Date().toString());
        pojo.setShippingDate(new Date());
        pojo.setAmountReturned(0);
        pojo.setAmtToBePaid(0);
//      pojo.setChequeNumber(pojo1.getChequeNo());
  //    pojo.setTotalCashPayment(pojo1.gett);
//      pojo.setTotalCashAmt(pojo1.getTotalFeeAmount());
//      pojo.setSiStatus(pojo1.getStatus());
//      pojo.setTotalVoucherPayment(pojo1.getTotalVoucherPayment());
//      pojo.setTotalCardPayment(pojo1.g);
//      pojo.setTotalCreditCardAmt(pojo1.);
        pojo.setSelectedItemsList(getItemToFee(pojo1));
//      pojo.setTaxSummaryList(pojo1.getTaxSummaryList());
//      pojo.setMultiPartialPaymentList(pojo1.getMultiPartialPaymentList());
//      pojo.setCashPayment(pojo1.getCashPayment());
//      pojo.setCreditPayment(pojo1.getCreditPayment());
//      pojo.setVoucherPayment(pojo1.getVoucherPayment());
//      pojo.setMultiPayment(pojo1.getMultiPayment());
//      pojo.setBankPayment(pojo1.getBankPayment());
//      pojo.setHiPosServiceCharge(pojo1.getHiPosServiceCharge());
//      pojo.setTermsId(pojo1.getTermsId());
//      pojo.setItemCount(pojo1.getItemCount());
//      pojo.setCompanydupData(pojo1.getCompanydupData());
//      pojo.setCompanyData(pojo1.getCompanyData());
//      pojo.setTermsId(pojo1.getTermsId());
//      pojo.setSelectedItemsList(pojo1.getSelectedItemsList());
//      pojo.setPrintType(pojo1.getPrintType());
//      pojo.setPaymentType(pojo1.getPaymentType());
//      pojo.setTotalCheckOutamt(pojo1.getTotalCheckOutamt());
//      pojo.setCessTotalTaxAmt(pojo1.getCessTotalTaxAmt());
//      pojo.setTaxType(pojo1.getTaxType());
//      pojo.setTotalServiceCharge(pojo1.getTotalServiceCharge());
//      pojo.setSiNo(pojo1.getSiNo());
//      pojo.setBalanceAmount(pojo1.getBalanceAmount());
//        pojo.setDiscountAmount(pojo1.getDiscountAmount());
//        pojo.setTotalTenderedAmount(pojo1.getTotalTenderedAmount());
//        pojo.setUserName(pojo1.getUserName());
//        pojo.setBillToAddress(pojo1.getBillToAddress());
//        pojo.setShipToAddress(pojo1.getShipToAddress());
//        pojo.setEmail(pojo1.getEmail());
//        pojo.setPhoneNumber(pojo1.getPhoneNumber());
//        pojo.setInventoryAddress(pojo1.getInventoryAddress());
//        pojo.setInventoryContactNo(pojo1.getInventoryContactNo());
//        pojo.setInventoryEmail(pojo1.getInventoryEmail());
//        pojo.setAdvancepayment(pojo1.getAdvancepayment());
//        pojo.setUser_id(pojo1.getUser_id());
//        pojo.setType_flag(pojo1.getType_flag());
//        pojo.setLocationAddress(pojo1.getLocationAddress());
//        pojo.setLocationState(pojo1.getLocationState());
//        pojo.setLocationGst(pojo1.getLocationGst());
//        pojo.setShippingDate(pojo1.getShippingDate());
//        pojo.setShippingReferenceNo(pojo1.getShippingReferenceNo());
//        pojo.setReferenceNo(pojo1.getReferenceNo());
//        pojo.setShippingmethodId(pojo1.getShippingmethodId());
//        pojo.setAgentName(pojo1.getAgentName());
//        pojo.setExchangerateValue(pojo1.getExchangerateValue());
//        pojo.setTc_value(pojo1.getTc_value());
//        pojo.setOtherContactId(pojo1.getOtherContactId());
//        pojo.setInvoiceDate(pojo1.getInvoiceDate());
//        pojo.setInvoiceAmt(pojo1.getInvoiceAmt());
//        pojo.setIncrementAmt(pojo1.getIncrementAmt());
//        pojo.setEmployeeId(pojo1.getEmployeeId());
//        pojo.setEmailSub(pojo1.getEmailSub());
//        pojo.setEmailBody(pojo1.getEmailBody());
//        pojo.setEmailInvoice(pojo1.getEmailInvoice());
//        pojo.setDiscountType(pojo1.getDiscountType());
//        pojo.setPiStatus(pojo1.getPiStatus());
//        pojo.setCustNotiId(pojo1.getCustNotiId());
//        pojo.setAdvancepayment(pojo.getAdvancepayment());
//        pojo.setAgentId(pojo.getAgentId());
//        pojo.setAgentIdOfInvoice(pojo.getAgentIdOfInvoice());
//        pojo.setAgentName(pojo.getAgentName());
//        pojo.setAmountReturned(pojo.getAmountReturned());
//        pojo.setInvoiceNo(pojo1.getInvoiceNo());
////retail
////        pojo.setSupplier(pojo1.getSupplier());
////        pojo.setSupplierId(pojo1.getSupplierId());
////        pojo.setAgentId(pojo1.getAgentId());
////        pojo.setExchangeRateId(pojo1.getExchangeRateId());
////        pojo.setApBalance(pojo1.getApBalance());
////        pojo.setPiid(pojo1.getPiid());
////        pojo.setSupplierEmail(pojo1.getSupplierEmail());
////        pojo.setPiNo(pojo1.getPiNo());
////        pojo.setPrlnNo(pojo1.getPrlnNo());
////        pojo.setSupplierName(pojo1.getSupplierName());
////        pojo.setSupplierInvNo(pojo1.getSupplierInvNo());
////        pojo.setCmpyLoc(pojo1.getCmpyLoc());
////        pojo.setSuppLoc(pojo1.getSuppLoc());
////        pojo.setSelfBuildInvoice(pojo1.getSelfBuildInvoice());
////        pojo.setSupplierAddress(pojo1.getSupplierAddress());
////        pojo.setSupplierState(pojo1.getSupplierState());
////        pojo.setSupplierGst(pojo1.getSupplierGst());
////        pojo.setLocationName(pojo1.getLocationName());
////        pojo.setLocationSupplierName(pojo1.getLocationSupplierName());
////        pojo.setExchangerateId(pojo1.getExchangerateId());
////        pojo.setCurrencyId(pojo1.getCurrencyId());
////        pojo.setProjectId(pojo1.getProjectId());
////        pojo.setTermsandConditionsId(pojo1.getTermsandConditionsId());
////        pojo.setPurchaseQuotationId(pojo1.getPurchaseQuotationId());
////        pojo.setPurchaseQuotationDetailsId(pojo1.getPurchaseQuotationDetailsId());
////        pojo.setPoId(pojo1.getPoId());
////        pojo.setPurchaseOrderId(pojo1.getPurchaseOrderId());
////        pojo.setReceiveItemId(pojo1.getReceiveItemId());
////        pojo.setDate(pojo1.getDate());
////        pojo.setTypeOfInvoice(pojo1.getTypeOfInvoice());
////        pojo.setCashAmtForReturn(pojo1.getCashAmtForReturn());
////        pojo.setChequeAmtForReturn(pojo1.getChequeAmtForReturn());
////        pojo.setDutyAmount(pojo1.getDutyAmount());
////        pojo.setFrightCharges(pojo1.getFrightCharges());
////        pojo.setOtherCharges(pojo1.getOtherCharges());
////        pojo.setTransactionId(pojo1.getTransactionId());
////        pojo.setNotificationId(pojo1.getNotificationId());
////        pojo.setTotaltax(pojo1.getTotaltax());
////        pojo.setFromCompname(pojo1.getFromCompname());
////        pojo.setToCompname(pojo1.getToCompname());
//        // purchase
//        pojo.setSalesQuotationDetailsId(pojo1.getSalesQuotationDetailsId());
//        pojo.setARBalance(pojo1.getARBalance());
//        pojo.setCustomer(pojo1.getCustomer());
//        pojo.setOperation(pojo1.getGeneratedVoucherNo());
//        pojo.setSiid(pojo1.getSiid());
//        pojo.setCustomerEmail(pojo1.getCustomerEmail());
//        pojo.setInventoryFax(pojo1.getInventoryFax());
//        pojo.setShippingDateString(pojo1.getShippingDateString());
//        pojo.setSalesOrderId(pojo1.getSalesOrderId());
//        pojo.setSalesOrderDetailsId(pojo1.getSalesOrderDetailsId());
//        pojo.setReturnReason(pojo1.getReturnReason());
//        pojo.setTotalRemaininBalance(pojo1.getTotalRemaininBalance());
//        pojo.setCustomerId(pojo1.getCustomerId());
//        pojo.setRedeemPayment(pojo1.getRedeemPayment());
//        pojo.setRecieptFooter(pojo1.getRecieptFooter());
//        pojo.setCompanyLogoPath(pojo1.getCompanyLogoPath());
//        pojo.setFormNo(pojo1.getFormNo());
//        pojo.setCmpyLocation(pojo1.getCmpyLocation());
//        pojo.setSrlnNo(pojo1.getSrlnNo());
//        pojo.setCustLocation(pojo1.getCustLocation());
//        pojo.setTokenNo(pojo1.getTokenNo());
//        pojo.setTable(pojo1.getTable());
//        pojo.setARBalance(pojo1.getARBalance());
//        pojo.setTotalCashPymtAmtReturned(pojo1.getTotalCashPymtAmtReturned());
//        pojo.setTotalChequePymtAmtReturned(pojo1.getTotalChequePymtAmtReturned());
//        pojo.setTotalVoucherPymtAmtReturned(pojo1.getTotalVoucherPymtAmtReturned());
//        pojo.setFormDate(pojo1.getFormDate());
//        pojo.setProjectName(pojo1.getProjectName());
//        pojo.setShippingMethodName(pojo1.getShippingMethodName());
//        pojo.setInvokeOrderId(pojo1.getInvokeOrderId());
//        pojo.setInvokeOrderName(pojo1.getInvokeOrderName());
//        pojo.setGeneratedVoucherNo(pojo1.getGeneratedVoucherNo());
//        pojo.setCustomerPo(pojo1.getCustomerPo());
//        pojo.setServiceDeliveryId(pojo1.getServiceDeliveryId());
//        pojo.setExportInvoice(pojo1.getExportInvoice());
//        pojo.setInvokeRemaningQty(pojo1.getInvokeRemaningQty());
//        pojo.setSalesQuotationId(pojo1.getSalesQuotationId());
//        pojo.setProFormaId(pojo1.getProFormaId());
//        pojo.setProFormaDetailsId(pojo1.getProFormaDetailsId());
//        pojo.setPatientId(pojo1.getPatientId());
//        pojo.setServiceCharge(pojo1.getServiceCharge());
//        pojo.setAgentIdOfInvoice(pojo1.getAgentIdOfInvoice());
//        pojo.setProjectIdOfInvoice(pojo1.getProjectIdOfInvoice());
//        pojo.setTermCondIdOfInvoice(pojo1.getTermCondIdOfInvoice());
//        pojo.setCurrencyIdOfInvoice(pojo1.getCurrencyIdOfInvoice());
//        pojo.setExchangeRateIdOfInvoice(pojo1.getExchangeRateIdOfInvoice());
        return pojo;
    }
    public static TransactionPojo feePaymentToTransaction(StudentFeeDto studentFeeDto){
        TransactionPojo pojo = new TransactionPojo();
        pojo.setFormNo(studentFeeDto.getStudentProfileId());
        pojo.setCustomerName(studentFeeDto.getStudentName());
        pojo.setAmtToBePaid(studentFeeDto.getTotalPaid());
        pojo.setTotalTenderedAmount(studentFeeDto.getPayingFee());
        pojo.setTotalCheckOutamt(studentFeeDto.getTotalPaid());
        pojo.setAmountReturned(studentFeeDto.getTotalPaid());
        pojo.setPaymentType(studentFeeDto.getPaymentType());
        pojo.setExchangerateValue("1");
        pojo.setCashPayment(getCashpaymentOBJ(studentFeeDto));
        pojo.setBankPayment(getBankPaymentOBJ(studentFeeDto));
        pojo.setVoucherPayment(getVoucherPaymentOBJ(studentFeeDto));
        pojo.setCreditPayment(getCreditCardPaymentOBJ(studentFeeDto));
        return pojo;
    }
    public static TransactionPojo salesToTransaction(StudentFeePojo pojo1) {
        TransactionPojo pojo = new TransactionPojo();
        pojo.setCheckForHoldStock(true);
        pojo.setCustomerName(pojo1.getStudentName());
        //  pojo.setCustomerName(pojo1.getStudentName());
        pojo.setTotalTaxAmt(0d);
        pojo.setFrom_reg("7F5F522AFBB14D4E");
        pojo.setTo_reg("7F5F522AFBB14D4E");
        pojo.setSubscriptionType("DesktopWithRTR");
        pojo.setTypeDoc("PI");
        pojo.setMemo("Fee Payment");
        pojo.setType_flag("Purchase");
        //  pojo.setType_flag("Sales");
        pojo.setSiNo("222222222222");
        pojo.setPaymentType("multiPayment");
        pojo.setDateOfInvoice(new Date().toString());
        pojo.setShippingDate(new Date());
        pojo.setAmountReturned(0);
        pojo.setAmtToBePaid(pojo1.getPayingAmount());
        pojo.setChequeNumber(pojo1.getChequeNo());
        pojo.setTotalCashPayment(pojo1.getTotalFeeAmount());
        pojo.setTotalCashAmt(pojo1.getTotalFeeAmount());
        pojo.setSiStatus(pojo1.getStatus());
//      pojo.setTotalVoucherPayment(pojo1.getTotalVoucherPayment());
//      pojo.setTotalCardPayment(pojo1.g);
//      pojo.setTotalCreditCardAmt(pojo1.);
//      pojo.setSelectedItemsList(getItemToFee(pojo1));
//      pojo.setTaxSummaryList(pojo1.getTaxSummaryList());
//      pojo.setMultiPartialPaymentList(pojo1.getMultiPartialPaymentList());
//      pojo.setCashPayment(pojo1.getCashPayment());
//      pojo.setCreditPayment(pojo1.getCreditPayment());
//      pojo.setVoucherPayment(pojo1.getVoucherPayment());
//      pojo.setMultiPayment(pojo1.getMultiPayment());
//      pojo.setBankPayment(pojo1.getBankPayment());
//      pojo.setHiPosServiceCharge(pojo1.getHiPosServiceCharge());
//      pojo.setTermsId(pojo1.getTermsId());
//      pojo.setItemCount(pojo1.getItemCount());
//      pojo.setCompanydupData(pojo1.getCompanydupData());
//      pojo.setCompanyData(pojo1.getCompanyData());
//        pojo.setTermsId(pojo1.getTermsId());
//        pojo.setSelectedItemsList(pojo1.getSelectedItemsList());
//        pojo.setPrintType(pojo1.getPrintType());
//        pojo.setPaymentType(pojo1.getPaymentType());
//        pojo.setTotalCheckOutamt(pojo1.getTotalCheckOutamt());
//        pojo.setCessTotalTaxAmt(pojo1.getCessTotalTaxAmt());
//        pojo.setTaxType(pojo1.getTaxType());
//        pojo.setTotalServiceCharge(pojo1.getTotalServiceCharge());
//        pojo.setSiNo(pojo1.getSiNo());
//        pojo.setBalanceAmount(pojo1.getBalanceAmount());
//        pojo.setDiscountAmount(pojo1.getDiscountAmount());
//        pojo.setTotalTenderedAmount(pojo1.getTotalTenderedAmount());
//        pojo.setUserName(pojo1.getUserName());
//        pojo.setBillToAddress(pojo1.getBillToAddress());
//        pojo.setShipToAddress(pojo1.getShipToAddress());
//        pojo.setEmail(pojo1.getEmail());
//        pojo.setPhoneNumber(pojo1.getPhoneNumber());
//        pojo.setInventoryAddress(pojo1.getInventoryAddress());
//        pojo.setInventoryContactNo(pojo1.getInventoryContactNo());
//        pojo.setInventoryEmail(pojo1.getInventoryEmail());
//        pojo.setAdvancepayment(pojo1.getAdvancepayment());
//        pojo.setUser_id(pojo1.getUser_id());
//        pojo.setType_flag(pojo1.getType_flag());
//        pojo.setLocationAddress(pojo1.getLocationAddress());
//        pojo.setLocationState(pojo1.getLocationState());
//        pojo.setLocationGst(pojo1.getLocationGst());
//        pojo.setShippingDate(pojo1.getShippingDate());
//        pojo.setShippingReferenceNo(pojo1.getShippingReferenceNo());
//        pojo.setReferenceNo(pojo1.getReferenceNo());
//        pojo.setShippingmethodId(pojo1.getShippingmethodId());
//        pojo.setAgentName(pojo1.getAgentName());
//        pojo.setExchangerateValue(pojo1.getExchangerateValue());
//        pojo.setTc_value(pojo1.getTc_value());
//        pojo.setOtherContactId(pojo1.getOtherContactId());
//        pojo.setInvoiceDate(pojo1.getInvoiceDate());
//        pojo.setInvoiceAmt(pojo1.getInvoiceAmt());
//        pojo.setIncrementAmt(pojo1.getIncrementAmt());
//        pojo.setEmployeeId(pojo1.getEmployeeId());
//        pojo.setEmailSub(pojo1.getEmailSub());
//        pojo.setEmailBody(pojo1.getEmailBody());
//        pojo.setEmailInvoice(pojo1.getEmailInvoice());
//        pojo.setDiscountType(pojo1.getDiscountType());
//        pojo.setPiStatus(pojo1.getPiStatus());
//        pojo.setCustNotiId(pojo1.getCustNotiId());
//        pojo.setAdvancepayment(pojo.getAdvancepayment());
//        pojo.setAgentId(pojo.getAgentId());
//        pojo.setAgentIdOfInvoice(pojo.getAgentIdOfInvoice());
//        pojo.setAgentName(pojo.getAgentName());
//        pojo.setAmountReturned(pojo.getAmountReturned());
//        pojo.setInvoiceNo(pojo1.getInvoiceNo());
//        retail
//        pojo.setSupplier(pojo1.getSupplier());
//        pojo.setSupplierId(pojo1.getSupplierId());
//        pojo.setAgentId(pojo1.getAgentId());
//        pojo.setExchangeRateId(pojo1.getExchangeRateId());
//        pojo.setApBalance(pojo1.getApBalance());
//        pojo.setPiid(pojo1.getPiid());
//        pojo.setSupplierEmail(pojo1.getSupplierEmail());
//        pojo.setPiNo(pojo1.getPiNo());
//        pojo.setPrlnNo(pojo1.getPrlnNo());
//        pojo.setSupplierName(pojo1.getSupplierName());
//        pojo.setSupplierInvNo(pojo1.getSupplierInvNo());
//          pojo.setCmpyLoc(pojo1.getCmpyLoc());
//          pojo.setSuppLoc(pojo1.getSuppLoc());
//          pojo.setSelfBuildInvoice(pojo1.getSelfBuildInvoice());
//          pojo.setSupplierAddress(pojo1.getSupplierAddress());
//          pojo.setSupplierState(pojo1.getSupplierState());
//          pojo.setSupplierGst(pojo1.getSupplierGst());
//          pojo.setLocationName(pojo1.getLocationName());
//          pojo.setLocationSupplierName(pojo1.getLocationSupplierName());
//        pojo.setExchangerateId(pojo1.getExchangerateId());
//        pojo.setCurrencyId(pojo1.getCurrencyId());
//        pojo.setProjectId(pojo1.getProjectId());
//        pojo.setTermsandConditionsId(pojo1.getTermsandConditionsId());
//        pojo.setPurchaseQuotationId(pojo1.getPurchaseQuotationId());
//        pojo.setPurchaseQuotationDetailsId(pojo1.getPurchaseQuotationDetailsId());
//        pojo.setPoId(pojo1.getPoId());
//        pojo.setPurchaseOrderId(pojo1.getPurchaseOrderId());
//        pojo.setReceiveItemId(pojo1.getReceiveItemId());
//        pojo.setDate(pojo1.getDate());
//        pojo.setTypeOfInvoice(pojo1.getTypeOfInvoice());
//        pojo.setCashAmtForReturn(pojo1.getCashAmtForReturn());
//        pojo.setChequeAmtForReturn(pojo1.getChequeAmtForReturn());
//        pojo.setDutyAmount(pojo1.getDutyAmount());
//        pojo.setFrightCharges(pojo1.getFrightCharges());
//        pojo.setOtherCharges(pojo1.getOtherCharges());
//        pojo.setTransactionId(pojo1.getTransactionId());
//        pojo.setNotificationId(pojo1.getNotificationId());
//        pojo.setTotaltax(pojo1.getTotaltax());
//        pojo.setFromCompname(pojo1.getFromCompname());
//        pojo.setToCompname(pojo1.getToCompname());
//        // purchase
//        pojo.setSalesQuotationDetailsId(pojo1.getSalesQuotationDetailsId());
//        pojo.setARBalance(pojo1.getARBalance());
//        pojo.setCustomer(pojo1.getCustomer());
//        pojo.setOperation(pojo1.getGeneratedVoucherNo());
//        pojo.setSiid(pojo1.getSiid());
//        pojo.setCustomerEmail(pojo1.getCustomerEmail());
//        pojo.setInventoryFax(pojo1.getInventoryFax());
//        pojo.setShippingDateString(pojo1.getShippingDateString());
//        pojo.setSalesOrderId(pojo1.getSalesOrderId());
//        pojo.setSalesOrderDetailsId(pojo1.getSalesOrderDetailsId());
//        pojo.setReturnReason(pojo1.getReturnReason());
//        pojo.setTotalRemaininBalance(pojo1.getTotalRemaininBalance());
//        pojo.setCustomerId(pojo1.getCustomerId());
//        pojo.setRedeemPayment(pojo1.getRedeemPayment());
//        pojo.setRecieptFooter(pojo1.getRecieptFooter());
//        pojo.setCompanyLogoPath(pojo1.getCompanyLogoPath());
//        pojo.setFormNo(pojo1.getFormNo());
//        pojo.setCmpyLocation(pojo1.getCmpyLocation());
//        pojo.setSrlnNo(pojo1.getSrlnNo());
//        pojo.setCustLocation(pojo1.getCustLocation());
//        pojo.setTokenNo(pojo1.getTokenNo());
//        pojo.setTable(pojo1.getTable());
//        pojo.setARBalance(pojo1.getARBalance());
//        pojo.setTotalCashPymtAmtReturned(pojo1.getTotalCashPymtAmtReturned());
//        pojo.setTotalChequePymtAmtReturned(pojo1.getTotalChequePymtAmtReturned());
//        pojo.setTotalVoucherPymtAmtReturned(pojo1.getTotalVoucherPymtAmtReturned());
//        pojo.setFormDate(pojo1.getFormDate());
//        pojo.setProjectName(pojo1.getProjectName());
//        pojo.setShippingMethodName(pojo1.getShippingMethodName());
//        pojo.setInvokeOrderId(pojo1.getInvokeOrderId());
//        pojo.setInvokeOrderName(pojo1.getInvokeOrderName());
//        pojo.setGeneratedVoucherNo(pojo1.getGeneratedVoucherNo());
//        pojo.setCustomerPo(pojo1.getCustomerPo());
//        pojo.setServiceDeliveryId(pojo1.getServiceDeliveryId());
//        pojo.setExportInvoice(pojo1.getExportInvoice());
//        pojo.setInvokeRemaningQty(pojo1.getInvokeRemaningQty());
//        pojo.setSalesQuotationId(pojo1.getSalesQuotationId());
//        pojo.setProFormaId(pojo1.getProFormaId());
//        pojo.setProFormaDetailsId(pojo1.getProFormaDetailsId());
//        pojo.setPatientId(pojo1.getPatientId());
//        pojo.setServiceCharge(pojo1.getServiceCharge());
//        pojo.setAgentIdOfInvoice(pojo1.getAgentIdOfInvoice());
//        pojo.setProjectIdOfInvoice(pojo1.getProjectIdOfInvoice());
//        pojo.setTermCondIdOfInvoice(pojo1.getTermCondIdOfInvoice());
//        pojo.setCurrencyIdOfInvoice(pojo1.getCurrencyIdOfInvoice());
//        pojo.setExchangeRateIdOfInvoice(pojo1.getExchangeRateIdOfInvoice());
        return pojo;
    }


    public static CashPayment getCashpaymentOBJ(StudentFeeDto studentFeeDto){
        CashPayment cashPayment=new CashPayment();
        cashPayment.setMultiCashPaymentList(getMultiCashPayment(studentFeeDto));
        return cashPayment;
    }
    public static BankPayment getBankPaymentOBJ(StudentFeeDto studentFeeDto){
        BankPayment bankPayment=new BankPayment();
        bankPayment.setMultiBankPaymentList(null);
        return bankPayment;
    }
    public static VoucherPayment getVoucherPaymentOBJ(StudentFeeDto studentFeeDto){
        VoucherPayment voucherPayment=new VoucherPayment();
        voucherPayment.setMultiVoucherPayments(null);
        return voucherPayment;
    }


    public static CreditCardPayment getCreditCardPaymentOBJ(StudentFeeDto studentFeeDto){
        CreditCardPayment creditCardPayment=new CreditCardPayment();
        creditCardPayment.setCardPaymentList(null);
        return creditCardPayment;
    }
    public static List<MultiCashPayment> getMultiCashPayment(StudentFeeDto studentFeeDto){
        List<MultiCashPayment> multiCashPayments=new ArrayList<>();
//        for(FeeTypeMasterPojo ss: studentFeeDto.getFeeTypeMasterPojoList()) {
            MultiCashPayment  multiCashPayment= new MultiCashPayment();
            multiCashPayment.setCashAmt(studentFeeDto.getCashAmt());
            multiCashPayment.setPaymentType("1");
            multiCashPayment.setTotalCPAmountRefunded(0);
            multiCashPayment.setTotalCPDiscount(0);
            multiCashPayments.add(multiCashPayment);
//        }
        return multiCashPayments;
    }


//    public static TransactionPojo purchaseToTransaction(PurchaseDTO pojo1) {
//        TransactionPojo pojo = new TransactionPojo();
//        pojo.setCheckForHoldStock(true);
//        pojo.setSelectedItemsList(pojo1.getSelectedItemsList());
//        pojo.setTaxSummaryList(pojo1.getTaxSummaryList());
//        pojo.setMultiPartialPaymentList(pojo1.getMultiPartialPaymentList());
//        pojo.setCashPayment(pojo1.getCashPayment());
//        pojo.setCreditPayment(pojo1.getCreditPayment());
//        pojo.setVoucherPayment(pojo1.getVoucherPayment());
//        pojo.setMultiPayment(pojo1.getMultiPayment());
//        pojo.setBankPayment(pojo1.getBankPayment());
//        pojo.setHiPosServiceCharge(pojo1.getHiPosServiceCharge());
//        pojo.setTermsId(pojo1.getTermsId());
//        pojo.setItemCount(pojo1.getItemCount());
//        pojo.setCompanydupData(pojo1.getCompanydupData());
//        pojo.setCompanyData(pojo1.getCompanyData());
//        pojo.setTermsId(pojo1.getTermsId());
//        pojo.setAmountReturned(pojo1.getAmountReturned());
//        pojo.setSelectedItemsList(pojo1.getSelectedItemsList());
//        pojo.setPrintType(pojo1.getPrintType());
//        pojo.setPaymentType(pojo1.getPaymentType());
//        pojo.setTotalCheckOutamt(pojo1.getTotalCheckOutamt());
//        pojo.setTotalTaxAmt(pojo1.getTotalTaxAmt());
//        pojo.setCessTotalTaxAmt(pojo1.getCessTotalTaxAmt());
//        pojo.setTaxType(pojo1.getTaxType());
//        pojo.setTotalServiceCharge(pojo1.getTotalServiceCharge());
//        pojo.setSiNo(pojo1.getSiNo());
//        pojo.setBalanceAmount(pojo1.getBalanceAmount());
//        pojo.setDiscountAmount(pojo1.getDiscountAmount());
//        pojo.setTotalTenderedAmount(pojo1.getTotalTenderedAmount());
//        pojo.setUserName(pojo1.getUserName());
//        pojo.setBillToAddress(pojo1.getBillToAddress());
//        pojo.setShipToAddress(pojo1.getShipToAddress());
//        pojo.setEmail(pojo1.getEmail());
//        pojo.setPhoneNumber(pojo1.getPhoneNumber());
//        pojo.setInventoryAddress(pojo1.getInventoryAddress());
//        pojo.setInventoryContactNo(pojo1.getInventoryContactNo());
//        pojo.setInventoryEmail(pojo1.getInventoryEmail());
//        pojo.setAdvancepayment(pojo1.getAdvancepayment());
//        pojo.setChequeNumber(pojo1.getChequeNumber());
//        pojo.setFrom_reg(pojo1.getFrom_reg());
//        pojo.setTo_reg(pojo1.getTo_reg());
//        pojo.setUser_id(pojo1.getUser_id());
//        pojo.setTypeDoc(pojo1.getTypeDoc());
//        pojo.setType_flag(pojo1.getType_flag());
//        pojo.setDateOfInvoice(pojo1.getDateOfInvoice());
//        pojo.setLocationAddress(pojo1.getLocationAddress());
//        pojo.setLocationState(pojo1.getLocationState());
//        pojo.setLocationGst(pojo1.getLocationGst());
//        pojo.setMemo(pojo1.getMemo());
//        pojo.setShippingDate(pojo1.getShippingDate());
//        pojo.setShippingReferenceNo(pojo1.getShippingReferenceNo());
//        pojo.setReferenceNo(pojo1.getReferenceNo());
//        pojo.setShippingmethodId(pojo1.getShippingmethodId());
//        pojo.setAgentName(pojo1.getAgentName());
//        pojo.setExchangerateValue(pojo1.getExchangerateValue());
//        pojo.setTc_value(pojo1.getTc_value());
//        pojo.setOtherContactId(pojo1.getOtherContactId());
//        pojo.setInvoiceDate(pojo1.getInvoiceDate());
//        pojo.setInvoiceAmt(pojo1.getInvoiceAmt());
//        pojo.setIncrementAmt(pojo1.getIncrementAmt());
//        pojo.setEmployeeId(pojo1.getEmployeeId());
//        pojo.setEmailSub(pojo1.getEmailSub());
//        pojo.setEmailBody(pojo1.getEmailBody());
//        pojo.setEmailInvoice(pojo1.getEmailInvoice());
//        pojo.setDiscountType(pojo1.getDiscountType());
//        pojo.setPiStatus(pojo1.getPiStatus());
//        pojo.setCustNotiId(pojo1.getCustNotiId());
//        pojo.setAdvancepayment(pojo.getAdvancepayment());
//        pojo.setAgentId(pojo.getAgentId());
//        pojo.setAgentIdOfInvoice(pojo.getAgentIdOfInvoice());
//        pojo.setAgentName(pojo.getAgentName());
//        pojo.setAmountReturned(pojo.getAmountReturned());
//        pojo.setAmtToBePaid(pojo.getAmtToBePaid());
//        pojo.setInvoiceNo(pojo1.getInvoiceNo());
//
//
////retail
//        pojo.setSupplier(pojo1.getSupplier());
//        pojo.setSupplierId(pojo1.getSupplierId());
//        pojo.setAgentId(pojo1.getAgentId());
//        pojo.setExchangeRateId(pojo1.getExchangeRateId());
//        pojo.setApBalance(pojo1.getApBalance());
//        pojo.setPiid(pojo1.getPiid());
//        pojo.setSupplierEmail(pojo1.getSupplierEmail());
//        pojo.setPiNo(pojo1.getPiNo());
//        pojo.setPrlnNo(pojo1.getPrlnNo());
//        pojo.setSupplierName(pojo1.getSupplierName());
//        pojo.setSupplierInvNo(pojo1.getSupplierInvNo());
//        pojo.setCmpyLoc(pojo1.getCmpyLoc());
//        pojo.setSuppLoc(pojo1.getSuppLoc());
//        pojo.setSelfBuildInvoice(pojo1.getSelfBuildInvoice());
//        pojo.setSupplierAddress(pojo1.getSupplierAddress());
//        pojo.setSupplierState(pojo1.getSupplierState());
//        pojo.setSupplierGst(pojo1.getSupplierGst());
//        pojo.setLocationName(pojo1.getLocationName());
//        pojo.setLocationSupplierName(pojo1.getLocationSupplierName());
//        pojo.setExchangerateId(pojo1.getExchangerateId());
//        pojo.setCurrencyId(pojo1.getCurrencyId());
//        pojo.setProjectId(pojo1.getProjectId());
//        pojo.setTermsandConditionsId(pojo1.getTermsandConditionsId());
//        pojo.setPurchaseQuotationId(pojo1.getPurchaseQuotationId());
//        pojo.setPurchaseQuotationDetailsId(pojo1.getPurchaseQuotationDetailsId());
//        pojo.setPoId(pojo1.getPoId());
//        pojo.setPurchaseOrderId(pojo1.getPurchaseOrderId());
//        pojo.setReceiveItemId(pojo1.getReceiveItemId());
//        pojo.setDate(pojo1.getDate());
//        pojo.setTypeOfInvoice(pojo1.getTypeOfInvoice());
//        pojo.setCashAmtForReturn(pojo1.getCashAmtForReturn());
//        pojo.setChequeAmtForReturn(pojo1.getChequeAmtForReturn());
//        pojo.setDutyAmount(pojo1.getDutyAmount());
//        pojo.setFrightCharges(pojo1.getFrightCharges());
//        pojo.setOtherCharges(pojo1.getOtherCharges());
//        pojo.setTransactionId(pojo1.getTransactionId());
//        pojo.setNotificationId(pojo1.getNotificationId());
//        pojo.setTotaltax(pojo1.getTotaltax());
//        pojo.setFromCompname(pojo1.getFromCompname());
//        pojo.setToCompname(pojo1.getToCompname());
//
//
//
//        // purchase
////        pojo.setSalesQuotationDetailsId(pojo1.getSalesQuotationDetailsId());
////        pojo.setARBalance(pojo1.getARBalance());
////        pojo.setCustomer(pojo1.getCustomer());
////        pojo.setOperation(pojo1.getGeneratedVoucherNo());
////        pojo.setSiid(pojo1.getSiid());
////        pojo.setCustomerEmail(pojo1.getCustomerEmail());
////        pojo.setInventoryFax(pojo1.getInventoryFax());
////        pojo.setShippingDateString(pojo1.getShippingDateString());
////        pojo.setSalesOrderId(pojo1.getSalesOrderId());
////        pojo.setSalesOrderDetailsId(pojo1.getSalesOrderDetailsId());
////        pojo.setReturnReason(pojo1.getReturnReason());
////        pojo.setTotalRemaininBalance(pojo1.getTotalRemaininBalance());
////        pojo.setCustomerId(pojo1.getCustomerId());
////        pojo.setRedeemPayment(pojo1.getRedeemPayment());
////        pojo.setRecieptFooter(pojo1.getRecieptFooter());
////        pojo.setCompanyLogoPath(pojo1.getCompanyLogoPath());
////        pojo.setFormNo(pojo1.getFormNo());
////        pojo.setCmpyLocation(pojo1.getCmpyLocation());
////        pojo.setSrlnNo(pojo1.getSrlnNo());
////        pojo.setCutomerName(pojo1.getCutomerName());
////        pojo.setCustLocation(pojo1.getCustLocation());
////        pojo.setCustomerName(pojo1.getCustomerName());
////        pojo.setTokenNo(pojo1.getTokenNo());
////        pojo.setTable(pojo1.getTable());
////        pojo.setARBalance(pojo1.getARBalance());
////        pojo.setTotalCashPymtAmtReturned(pojo1.getTotalCashPymtAmtReturned());
////        pojo.setTotalChequePymtAmtReturned(pojo1.getTotalChequePymtAmtReturned());
////        pojo.setTotalVoucherPymtAmtReturned(pojo1.getTotalVoucherPymtAmtReturned());
////        pojo.setFormDate(pojo1.getFormDate());
////        pojo.setProjectName(pojo1.getProjectName());
////        pojo.setShippingMethodName(pojo1.getShippingMethodName());
////        pojo.setInvokeOrderId(pojo1.getInvokeOrderId());
////        pojo.setInvokeOrderName(pojo1.getInvokeOrderName());
////        pojo.setGeneratedVoucherNo(pojo1.getGeneratedVoucherNo());
////        pojo.setCustomerPo(pojo1.getCustomerPo());
////        pojo.setServiceDeliveryId(pojo1.getServiceDeliveryId());
////        pojo.setExportInvoice(pojo1.getExportInvoice());
////        pojo.setInvokeRemaningQty(pojo1.getInvokeRemaningQty());
////        pojo.setAmtToBePaid(pojo1.getAmtToBePaid());
////        pojo.setSiStatus(pojo1.getSiStatus());
////        pojo.setSalesQuotationId(pojo1.getSalesQuotationId());
////        pojo.setProFormaId(pojo1.getProFormaId());
////        pojo.setProFormaDetailsId(pojo1.getProFormaDetailsId());
////        pojo.setTotalVoucherAmt(pojo1.getTotalVoucherAmt());
////        pojo.setTotalCreditCardAmt(pojo1.getTotalCreditCardAmt());
////        pojo.setTotalCashAmt(pojo1.getTotalCashAmt());
////        pojo.setPatientId(pojo1.getPatientId());
////        pojo.setServiceCharge(pojo1.getServiceCharge());
////        pojo.setAgentIdOfInvoice(pojo1.getAgentIdOfInvoice());
////        pojo.setProjectIdOfInvoice(pojo1.getProjectIdOfInvoice());
////        pojo.setTermCondIdOfInvoice(pojo1.getTermCondIdOfInvoice());
////        pojo.setCurrencyIdOfInvoice(pojo1.getCurrencyIdOfInvoice());
////        pojo.setExchangeRateIdOfInvoice(pojo1.getExchangeRateIdOfInvoice());
////        pojo.setTotalCashPayment(pojo1.getTotalCashPayment());
////        pojo.setTotalVoucherPayment(pojo1.getTotalVoucherPayment());
////        pojo.setTotalCardPayment(pojo1.getTotalCardPayment());
////        pojo.setCustomerAddress(pojo1.getCustomerAddress());
////        pojo.setCustomerState(pojo1.getCustomerState());
////        pojo.setCustomerGst(pojo1.getCustomerGst());
//
//
//        return pojo;
//    }
}